### ISSUE TITLE
Absolutely a wonderful project!

### ISSUE THREAD

**Issue by ghost** [torcado194/worm#3]
I wonder if you could make the visualizer more _clear_ ? I think it is too messy. Or creating a visualizer application? That will be far more interesting.

**Comment by torcado194** [comment]
Thanks for the compliment!
It is difficult to fit enough useful information in a terminal window while supporting a small enough screen size that most people can use.
At some point i may rewrite the visualizer script, but that would mostly only make the glitching less common, not change the overall layout significantly.
A standalone visualizer application would be neat! The goal with the visualizer was to try making a GUI in the terminal, just for fun. Maybe in the future i'll consider a standalone program for it :)
